services:
  sqlsrv:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlsrv
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$MSSQL_SA_PASSWORD\" -C -Q \"SELECT 1\"" ]
      interval: 10s
      timeout: 3s
      retries: 30
      start_period: 20s

  api:
    build:
      context: .
      dockerfile: Contracts.Api/Dockerfile
    container_name: contracts-api
    environment:
        ConnectionStrings__ContractsDb: "Server=sqlsrv,1433;Database=ContractsDb;User Id=sa;Password=Qwopzx!2025;Encrypt=False;MultipleActiveResultSets=True"
    ports:
      - "8080:8080"
    depends_on:
      sqlsrv:
        condition: service_healthy

volumes:
  mssql-data:
